### ISSUE TITLE
Hue Gradient LEDStrip (per zone control/ambilight)

### ISSUE THREAD

**Issue by p3tAbyte** [hyperion-project/hyperion.ng#1347]
#### What problem does this feature solve?
Hue Gradient LEDStrip can't be controled to feature more then 1 color at the time.
Since a couple of days it's possible in the APP to controle 3 of the 7 zones on a Hue Gradient LEDStrip.
Within the API it's possible to address all 7 zones. These zones are in fixed places within the strip size (55" / 65" / 75")

#### What does the proposed API look like?
REST Api
https://developers.meethue.com/develop/get-started-2/

#### How should this be implemented in your opinion?
When setting up a light source that is Hue and one starts the entertainment control, there should be a check
for the gradient LEDstrip. When detected the size should be confirmed by the user.

#### Are you willing to work on this yourself?
Absolutely! :D
Although my experience in developing is zero...

**Comment by mike689** [comment]
I'd love this feature too! The Hue HDMI Sync Box left a bad taste in my mouth, but hyperion has been simple and amazing!
Except for the one issue that my Hue gradient lightstrip will on do single colors. Would truly love this implemented!

**Comment by gotschi** [comment]
++ from me,
this would make it perfect for me as my LG CX WebOS just got rooted and PicCap sends the image successfuly to Hyperion.

But I can only use the gradient as a single bulb yet

**Comment by kopiro** [comment]
Hello; is this feature possible to impement? I'd love to help but I would like to know if it's theoretically possible :)

**Comment by gotschi** [comment]
> Hello; is this feature possible to impement? I'd love to help but I would like to know if it's theoretically possible :)

this is doable yes

**Comment by An0n22** [comment]
Just gonna add a +1 from me 👍 If this could be implemented I would be very happy :)

**Comment by gotschi** [comment]
I just built a container with https://github.com/jdmg94/Hue-Sync
and output via file from hyperion to it.

hyperion now works like a charm with the hue gradient strip, no sync box needed

**Comment by Eeleco** [comment]
Cool, but.. can you integrate it to Hyperion?

**Comment by claytonharris42** [comment]
> I just built a container with https://github.com/jdmg94/Hue-Sync and output via file from hyperion to it.

@gotschi Anyway you could provide a simple tutorial on what you've done there?

I've got your same setup (Hue Gradient, rooted LG OLED, PicCap, Hyperion, and a pi) but am limited to following instructions and tinkering. I don't really know where to start to follow your approach.

**Comment by nonamejuju** [comment]
Yes a tutorial will be good 👍

**Comment by gotschi** [comment]
> @gotschi Anyway you could provide a simple tutorial on what you've done there?

This is the script:
```ts
import HueSync from "hue-sync";
const fs = require('fs')
const path = require('path');

(async function () {
	const bridge = await HueSync.discover();
   
        // read fifo
	const fd = fs.openSync('/tmp/fifo', 'r+')
	const stream = fs.createReadStream(null, {fd})

        // login
	const credentials = {username:'username',clientkey:'clientkey'}
	const hueBridge = new HueSync({ credentials, id: 'id', url: 'ip' });
        
        // select entertainment area
	const selectedArea = await hueBridge.getEntertainmentAreas();
	await hueBridge.start(selectedArea[x]);

	stream.on('data',async (d) => {
                 // read matrix to array
		var data = d.toString().replace(/}/g, ',').replace(/[^0-9&,]/g,'').split(",");
		var data = data.map(function (x) { 
			return parseInt(x, 10); 
		});
                 
                 // send colors
		await hueBridge.transition([[data[0],data[1],data[2]],[data[3],data[4],data[5]],[data[6],data[7],data[8]],[data[9],data[10],data[11]],[data[12],data[13],data[14]],[data[15],data[16],data[17]],[data[18],data[19],data[20]]]);
	})

})()
```

You generally need npm/hue-sync for this (I would not recommend trying this on your tv, use a raspberry pi or something), I used a docker container:
```
FROM node:alpine
COPY app /app
WORKDIR /app
RUN npm install hue-sync
RUN npm install -g ts-node
CMD ['TS_NODE_FILES=true', 'TS_NODE_TRANSPILE_ONLY=true', 'NODE_TLS_REJECT_UNAUTHORIZED=0', 'ts-node', 'index.ts']
```
then you just need to modify the script to get the user/token from your hub:
https://github.com/jdmg94/Hue-Sync#usage
and use these in my script afterwards.
use this layout in hyperion: https://imgur.com/a/59gzAi8
make hyperion output to a fifo (`mkfifo huesync`) with the file LED Output controller and share this fifo with the huesync container like:

```yaml
version: '3'
services:
  hyperion:
    network_mode: host
    container_name: hyperion
    image: registry.gitlab.com/gotschi/hyperion
    volumes:
      - ./config:/root/.hyperion:rw
      - ./fifo:/tmp/fifo
    
  huesync:
    container_name: huesync
    image: huesync
    volumes:
      - ./fifo:/tmp/fifo
```

maybe I will make a standalone container image out of it when I get time

**Comment by gotschi** [comment]
> > I just built a container with https://github.com/jdmg94/Hue-Sync and output via file from hyperion to it.
> 
> @gotschi Anyway you could provide a simple tutorial on what you've done there?
> 
> I've got your same setup (Hue Gradient, rooted LG OLED, PicCap, Hyperion, and a pi) but am limited to following instructions and tinkering. I don't really know where to start to follow your approach.

finished the container,
use

```docker run --network host -v /home/youruser/huesync/config_huesync:/app/config -ti registry.gitlab.com/gotschi/hue-sync```

then do a `mkfifo fifo` in the folder

and follow the instructions.

then use the docker-compose I use from above with the persistent config directory you created:
```yaml
version: '3'
services:
  hyperion:
    network_mode: host
    container_name: hyperion
    image: hyperion
    volumes:
      - ./config:/root/.hyperion:rw
      - ./fifo:/tmp/fifo
    
  huesync:
    container_name: huesync
    image: huesync
    volumes:
      - ./config_huesync:/app/config
      - ./fifo:/tmp/fifo
```

lmk if it works for you
