### ISSUE TITLE
ESPHome neopixelbus detected as a single LED?

### ISSUE THREAD

**Issue by INPoppoRTUNE** [hyperion-project/hyperion.ng#1859]
- [x] I confirm that this is an issue rather than a question.

## Bug report
I'm trying to switch ESP32 firmware from WLED to [ESPHome neopixelbus](https://esphome.io/components/light/neopixelbus.html), but the strip is being detected as 1 LED long. 'Identify" button turn on all 241 LEDs.
```yaml
esphome:
  name: tizen-ambilight-leds
  friendly_name: tizen_ambilight_leds

esp32:
  board: esp32dev
  framework:
    type: arduino

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

[...]

light:
  - platform: neopixelbus
    type: GRB
    variant: WS2812
    pin: GPIO23
    num_leds: 241
    name: "LED Strip"
    restore_mode: ALWAYS_OFF
    effects:
      - addressable_scan:
```
If I trigger the [addressable_scan](https://esphome.io/components/light/index.html#addressable-scan-effect) effect Home Assistant is able to correctly address the single LEDs.
#### Steps to reproduce

![Image](https://github.com/user-attachments/assets/353446a4-9b92-4383-87b7-12886afc1b42)
The "Hardware LED count" field is unwritable.
Also the "LED position layout wizard" button seems to do nothing(?)

![Image](https://github.com/user-attachments/assets/e137f0e3-8902-40fe-a163-7d6149e52872)

#### What is expected?
It should detect 241 LEDs.

#### What is actually happening?
It detect all LEDs as one.

#### System

Hyperion Server:
- Build:             LordGrey-56aa545/d5664b6-1744986564
- Build time:        Apr 19 2025 01:22:16
- Build type:        Release
- Git Remote:        https://github.com/hyperion-project/hyperion.ng
- Version:           2.0.17-beta.3+nightly20250419d5664b6411a4eccc2f7ba083785d7b0a0391cf89
- UI Lang:           en (BrowserLang: en-US)
- UI Access:         default
- Avail Screen Cap.: framebuffer,x11,xcb,qt
- Avail Video  Cap.: v4l2
- Avail Audio  Cap.: audio
- Avail Services:    boblight,cec,effectengine,forwarder,flatbuffer,protobuffer,mDNS,SSDP,borderdetection
- Config database:   /root/.hyperion/db/hyperion.db
- Database:          read/write
- Mode:              Non-GUI

Hyperion Server OS:
- Distribution:      Ubuntu 22.04.5 LTS
- Architecture:      x86_64
- CPU Model:         Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz
- CPU Type:          60
- Kernel:            linux (6.6.78-Unraid (WS: 64))
- Root/Admin:        true
- Qt Version:        6.2.4
- Python Version:    3.10.12
- Browser:           Mozilla/5.0 (X11; Linux x86_64; rv:137.0) Gecko/20100101 Firefox/137.0
